---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos6
    driver:
      box: geerlingguy/centos6

suites:
  - name: default
    run_list:
      - recipe[yum_dag::default]
    attributes:
      yum_dag:
        upstreams:
          - repo_id: repo_a