---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos6
    driver:
      box: geerlingguy/centos6

suites:
  - name: node_a
    driver:
      network:
        - ["private_network", {ip: "192.168.20.2"}]
    run_list:
      - recipe[yum_dag::seed_packages]
      - recipe[yum_dag::create_repo]
      - recipe[yum_dag::enable_downstreams]
    attributes:
      yum_dag:
        seed_packages:
          repotrack:
            - createrepo
            - httpd
  - name: node_b
    driver:
      network:
        - ["private_network", {ip: "192.168.20.3"}]
    run_list:
      - recipe[yum_dag::remove_other_upstreams]
      - recipe[yum_dag::add_upstreams]
      - recipe[yum_dag::sync_to_upstreams]
      - recipe[yum_dag::create_repo]
      - recipe[yum_dag::enable_downstreams]
    attributes:
      yum_dag:
        upstreams:
          - repoid: node_a
            description: "Node A"
            baseurl: "http://192.168.20.2/"
  - name: node_c
    driver:
      network:
        - ["private_network", {ip: "192.168.20.4"}]
    run_list:
      - recipe[yum_dag::remove_other_upstreams]
      - recipe[yum_dag::add_upstreams]
      - recipe[yum_dag::sync_to_upstreams]
      - recipe[yum_dag::create_repo]
    attributes:
      yum_dag:
        upstreams:
          - repoid: node_a
            description: "Node A"
            baseurl: "http://192.168.20.2/"
          - repoid: node_b
            description: "Node B"
            baseurl: "http://192.168.20.3/"