name 'yum_dag'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures yum_dag'
long_description 'Installs/Configures yum_dag'
version '0.1.0'
